compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# Note: Avoid hard-requiring env vars during local commands.
# GitHub Packages auth is handled in CI via environment or .npmrc.
# If needed for local publish, set GITHUB_TOKEN in your shell before running yarn.
# npmRegistries:
#   "https://npm.pkg.github.com":
#     npmAuthToken: "${GITHUB_TOKEN}"

yarnPath: .yarn/releases/yarn-4.9.4.cjs
