jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: alienfast/ci-node:6.0
    steps:
      - checkout
      - add_ssh_keys
      - run: ncu -u
      # allow the lock file to change
      - run: yarn install --no-immutable
      - run: yarn test
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ];
              then \
                 yarn releaseAuto && yarn npm publish
            fi
          name: Release and publish
    working_directory: ~/project
version: 2
